import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/global.scss";
import Header from "@/components/header";
import Footer from "@/components/footer";
import TanStackProvider from '@/providers/TanStackProvider';
import { GeneralStoreProvider } from '@/providers/GeneralStoreProvider'

import { Flowbite, ThemeModeScript } from "flowbite-react";

const inter = Inter({ subsets: ["latin"] });

interface RootLayoutProps {
  children: React.ReactNode;
  locale: never;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, locale }: RootLayoutProps) {
  return (
    <html lang={locale} >
      <body className={inter.className} suppressHydrationWarning={true}>
        <GeneralStoreProvider>
        <TanStackProvider>
        <div>
        <Header />
        {children}
        <Footer/>
        </div>
        </TanStackProvider>
        </GeneralStoreProvider>
      </body>
    </html>
  );
}
